# TensorFlow - Quick start for beginners

Source: https://www.tensorflow.org/tutorials/quickstart/beginner

In [77]:
import tensorflow as tf

In [78]:
mnist = tf.keras.datasets.mnist

(xtrain, ytrain), (xtest, ytest) = mnist.load_data()
xtrain, xtest = xtrain / 255, xtest / 255

In [79]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)),
    tf.keras.layers.Dense(128, activation="relu"),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

In [80]:
predictions = model(xtrain[:1]).numpy()
predictions

array([[ 0.1176789 , -0.3966088 ,  0.43113282, -0.02986228, -0.43320072,
         0.34119868,  0.58518624, -0.18155202,  0.37810233, -0.5884793 ]],
      dtype=float32)

In [81]:
tf.nn.softmax(predictions).numpy()

array([[0.10220534, 0.06111127, 0.13983147, 0.08818553, 0.05891551,
        0.12780476, 0.16312085, 0.07577384, 0.13260934, 0.05044208]],
      dtype=float32)

In [82]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [83]:
loss_fn(ytrain[:1], predictions).numpy()

2.0572515

In [84]:
model.compile(optimizer="adam", loss=loss_fn, metrics=["accuracy"])

In [85]:
model.fit(xtrain, ytrain, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 2s 933us/step - loss: 0.3046 - accuracy: 0.9116
Epoch 2/5
1875/1875 [==============================] - 2s 934us/step - loss: 0.1494 - accuracy: 0.9557
Epoch 3/5
1875/1875 [==============================] - 2s 936us/step - loss: 0.1105 - accuracy: 0.9672
Epoch 4/5
1875/1875 [==============================] - 2s 937us/step - loss: 0.0915 - accuracy: 0.9719
Epoch 5/5
1875/1875 [==============================] - 2s 938us/step - loss: 0.0782 - accuracy: 0.9762


In [86]:
model.evaluate(xtest, ytest, verbose=2)

313/313 - 0s - loss: 0.0798 - accuracy: 0.9756


[0.07980338484048843, 0.975600004196167]

In [88]:
probability_model = tf.keras.Sequential([
    model,
    tf.keras.layers.Softmax()
])

In [91]:
probability_model(xtest[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[2.69776468e-08, 1.19889037e-07, 1.02477325e-05, 2.86979412e-05,
        4.97612923e-11, 6.33879580e-08, 4.41152614e-14, 9.99959707e-01,
        3.69003345e-07, 8.88918578e-07],
       [2.61580357e-08, 1.33884780e-03, 9.98226702e-01, 3.96007294e-04,
        5.92950642e-14, 3.66733220e-05, 1.04664025e-06, 7.12275779e-13,
        6.76783372e-07, 9.18163223e-13],
       [1.04162524e-07, 9.97368455e-01, 3.24380235e-04, 3.30147304e-05,
        1.08727887e-04, 8.93610704e-05, 1.23735354e-05, 1.77036459e-03,
        2.90615077e-04, 2.58286218e-06],
       [9.99817312e-01, 1.75385779e-07, 3.98422599e-05, 1.72569141e-08,
        8.67157212e-07, 6.13515704e-06, 2.55095292e-05, 9.37355944e-05,
        1.68183298e-08, 1.66760365e-05],
       [1.91282027e-07, 6.41255848e-09, 8.21093181e-06, 7.04280412e-09,
        9.99595582e-01, 6.29635650e-08, 2.13724434e-06, 1.10544512e-04,
        4.42899051e-07, 2.82654102e-04]], dtype=float32)>